// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class Cars
{
    public int ID { get; set; }

    public string CarModel { get; set; }

    public int Year { get; set; }
}