// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class Laps
{
    public decimal ID { get; set; }

    public decimal IDSession { get; set; }

    public int carId { get; set; }

    public int driverIndex { get; set; }

    public int numLap { get; set; }

    public string laptime { get; set; }

    public bool isValidForBest { get; set; }

    public string Sector1 { get; set; }

    public string Sector2 { get; set; }

    public string Sector3 { get; set; }

    public decimal LaptimeNumeric { get; set; }

    public decimal Sector1Numeric { get; set; }

    public decimal Sector2Numeric { get; set; }

    public decimal Sector3Numeric { get; set; }

    public bool IsTestSession { get; set; }

    public decimal IdSeasonForPractice { get; set; }
}