// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class LeaderBoard
{
    public decimal ID { get; set; }

    public decimal IDSession { get; set; }

    public int carId { get; set; }

    public int carModel { get; set; }

    public string carGroup { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public int currentDriverIndex { get; set; }

    public string lastLap { get; set; }

    public string LastSector1 { get; set; }

    public string LastSector2 { get; set; }

    public string LastSector3 { get; set; }

    public string BestLap { get; set; }

    public string BestSector1 { get; set; }

    public string BestSector2 { get; set; }

    public string BestSector3 { get; set; }

    public string TotalTime { get; set; }

    public int LapCount { get; set; }

    public bool missingMandatoryPitstop { get; set; }

    public int Position { get; set; }

    public decimal BestLapNumeric { get; set; }

    public decimal BestSector1Numeric { get; set; }

    public decimal BestSector2Numeric { get; set; }

    public decimal BestSector3Numeric { get; set; }

    public decimal TotalTimeNumeric { get; set; }

    public decimal? lastLapNumeric { get; set; }

    public decimal? LastSector1Numeric { get; set; }

    public decimal? LastSector2Numeric { get; set; }

    public decimal? LastSector3Numeric { get; set; }

    public bool IsTestSession { get; set; }
}