// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class penalties
{
    public decimal ID { get; set; }

    public decimal IDSession { get; set; }

    public int carId { get; set; }

    public int driverIndex { get; set; }

    public string reason { get; set; }

    public string penalty { get; set; }

    public int penaltyvalue { get; set; }

    public int violationInLap { get; set; }

    public int clearedInLap { get; set; }
}