// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class SeasonClassification
{
    public decimal ID { get; set; }

    public decimal IDSeason { get; set; }

    public decimal IDSession { get; set; }

    public decimal IDCalendar { get; set; }

    public string NickName { get; set; }

    public int Position { get; set; }

    public int carid { get; set; }

    public int PointsByParticipate { get; set; }

    public int PointByHotLap { get; set; }

    public int PointByPole { get; set; }

    public int TotalByPos { get; set; }

    public int TotalPoints { get; set; }
}