// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class SeasonSessions
{
    public decimal IdSeason { get; set; }

    public decimal IdSession { get; set; }
}