// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class SeasonPointsDefinition
{
    public decimal IDSeason { get; set; }

    public int RaceType { get; set; }

    public int Position { get; set; }

    public int Points { get; set; }
}