// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class SeasonCalendar
{
    public decimal ID { get; set; }

    public decimal IdSeason { get; set; }

    public int Order { get; set; }

    public decimal IdTrack { get; set; }

    public DateTime Date { get; set; }

    public TimeSpan Hour { get; set; }

    public int IDRaceType { get; set; }

    public bool OnlySumFirstQualy { get; set; }
}