// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class Sessions
{
    public decimal ID { get; set; }

    public string sessionType { get; set; }

    public string trackName { get; set; }

    public string LogFileName { get; set; }

    public string BestLap { get; set; }

    public string BestSector1 { get; set; }

    public string BestSector2 { get; set; }

    public string BestSector3 { get; set; }

    public bool IsWet { get; set; }

    public DateTime SessionDate { get; set; }

    public string SessionHour { get; set; }

    public decimal? IDQualySession { get; set; }

    public decimal BestLapNumeric { get; set; }

    public decimal BestSector1Numeric { get; set; }

    public decimal BestSector2Numeric { get; set; }

    public decimal BestSector3Numeric { get; set; }

    public bool IsTestSession { get; set; }

    public decimal IdSeasonForPractice { get; set; }

}