// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class TeamsByRace
{
    public decimal ID { get; set; }

    public decimal IDRace { get; set; }

    public string GameTag { get; set; }

    public string GameTagUID { get; set; }

    public string TeamName { get; set; }

    public int PilotOrder { get; set; }
}