// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class Tracks
{
    public decimal ID { get; set; }

    public string TrackName { get; set; }

    public string Lat { get; set; }

    public string Lon { get; set; }
}