// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class vGetRaceCSVFile
{
    public decimal IDSession { get; set; }

    public DateTime SessionDate { get; set; }

    public string SessionHour { get; set; }

    public string IdTemporada { get; set; }

    public string IdCircuit { get; set; }

    public string GameTag { get; set; }

    public long? Posicio { get; set; }

    public int PenalitzacioTemps { get; set; }

    public int PenalitzacioBoxes { get; set; }

    public string Pole { get; set; }

    public string VoltaRapida { get; set; }

    public string CursaLlarga { get; set; }

    public int PuntsPossicio { get; set; }

    public int? PuntsExtres { get; set; }

    public string InfoPuntsExtres { get; set; }

    public int? PuntsTotals { get; set; }
}