// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class vGetCountRacesCurSeasson
{
    public int? CurrentRaces { get; set; }

    public int? TotalRaces { get; set; }
}