// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class vGetGDIClassification
{

    public string IdTemporada { get; set; }

    public int? Posicio { get; set; }

    public string GameTag { get; set; }

    public int? Puntuacio { get; set; }

    public int? DiffPunts { get; set; }

    public int? PosLastRace { get; set; }

    public int? PointsLastRace { get; set; }

    public int? GainPos { get; set; }

    public int? GainPoints { get; set; }
}