// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class vGetQualyResult
{
    public string trackName { get; set; }

    public string CarModel { get; set; }

    public string lastName { get; set; }

    public string Driver { get; set; }

    public string BestLap { get; set; }

    public int Position { get; set; }

    public long GeneralPos { get; set; }

    public byte[] Photo { get; set; }
}