// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class vSeasonRaceLeaderBoard
{
    public string Season { get; set; }

    public DateTime DateStart { get; set; }

    public DateTime DateEnd { get; set; }

    public decimal IDSession { get; set; }

    public decimal? IDQualySession { get; set; }

    public DateTime SessionDate { get; set; }

    public string SessionHour { get; set; }

    public string Session { get; set; }

    public string TrackName { get; set; }

    public string BestLapSession { get; set; }

    public string BestSector1Session { get; set; }

    public string BestSector2Session { get; set; }

    public string BestSector3Session { get; set; }

    public string RaceMeteorology { get; set; }

    public string CarModel { get; set; }

    public string NickName { get; set; }

    public string BestLap { get; set; }

    public string BestSector1 { get; set; }

    public string BestSector2 { get; set; }

    public string BestSector3 { get; set; }

    public string LastLap { get; set; }

    public string LastSector1 { get; set; }

    public string LastSector2 { get; set; }

    public string LastSector3 { get; set; }

    public int LapCount { get; set; }

    public int Position { get; set; }

    public decimal BestLapNumeric { get; set; }

    public decimal BestSector1Numeric { get; set; }

    public decimal BestSector2Numeric { get; set; }

    public decimal BestSector3Numeric { get; set; }

    public decimal TotalTimeNumeric { get; set; }
}