// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class vSessionLaps
{
    public string Season { get; set; }

    public DateTime? DateStart { get; set; }

    public DateTime? DateEnd { get; set; }

    public decimal IDSession { get; set; }

    public decimal? IDQualySession { get; set; }

    public DateTime SessionDate { get; set; }

    public string SessionHour { get; set; }

    public string Session { get; set; }

    public string TrackName { get; set; }

    public string BestLapSession { get; set; }

    public string BestSector1Session { get; set; }

    public string BestSector2Session { get; set; }

    public string BestSector3Session { get; set; }

    public decimal BestLapNumeric { get; set; }

    public decimal BestSector1Numeric { get; set; }

    public decimal BestSector2Numeric { get; set; }

    public decimal BestSector3Numeric { get; set; }

    public string RaceMeteorology { get; set; }

    public string NickName { get; set; }

    public int numLap { get; set; }

    public bool isValidForBest { get; set; }

    public string laptime { get; set; }

    public string Sector1 { get; set; }

    public string Sector2 { get; set; }

    public string Sector3 { get; set; }

    public long? Position { get; set; }
}