// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class vSessionPenalties
{
    public decimal IDSession { get; set; }

    public string NickName { get; set; }

    public string penalty { get; set; }

    public string reason { get; set; }

    public int violationInLap { get; set; }

    public int clearedInLap { get; set; }
}