// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ACCLoadResults.Models;

public partial class vStatsRaceVsQualy
{
    public decimal IDSession { get; set; }

    public decimal? IDQualySession { get; set; }

    public DateTime SessionDate { get; set; }

    public string RaceMeteorology { get; set; }

    public string CarModel { get; set; }

    public string TrackName { get; set; }

    public string NickName { get; set; }

    public int StartPosition { get; set; }

    public int FinalPosition { get; set; }

    public int? DiffPosition { get; set; }

    public string HotLapRace { get; set; }

    public string HotLapPlayerRace { get; set; }

    public string PolePosition { get; set; }

    public string HotLapQualy { get; set; }

    public int LapsInRace { get; set; }

    public int LapsInQualy { get; set; }

    public string TotalTime { get; set; }

    public decimal? Diff { get; set; }
}